### ISSUE TITLE
Re-rendering service has frequent timeout issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#157]
As re-rendering takes longer than Heroku expects, we get frequent timeout issues. If possible, it would be good to extend the timeout.

**Comment by isuruf** [comment]
I think what's better would be to have a worker dyno do the re-rendering. (might need to buy a worker dyno though)

**Comment by pelson** [comment]
I don't know that we are utilising our resources at 100%, simply spiking above that, so simply making the whole thing async and using keep-alive effectively might suffice.

**Comment by CJ-Wright** [comment]
How hard can we push the re-render service? Currently the version bumping bot is doing re-renders before creating a PR, but that limits the speed with which it can bump the versions on things, so ideally the re-render would be farmed out to the service, but we may have a lot of service calls in a short time window.

@isuruf I think we talked about this in the past, but it might be nice to have firm numbers/cases where the service fell over due to being swamped.

**Comment by isuruf** [comment]
I don't have numbers. I don't think we should issue lot of PRs per day. When we had our maintenance bot working, there were only 20 PRs issued per day.

**Comment by jakirkham** [comment]
My impression is re-rendering with `conda-smithy` 3 is faster than `conda-smithy` 2, but have not measured it nor tested it in that many cases.

In your opinion @CJ-Wright, is this something we need to get on top of soon or is this something we can keep an eye on and reevaluate in time (e.g. maybe a month?)?

**Comment by CJ-Wright** [comment]
I think we can reevaluate, especially if `conda-smithy` 3 is faster.

**Comment by jakirkham** [comment]
Independently we might want to discuss how to move the current work into a web service. This should mitigate the extent to which things like re-rendering time impact update PRs sent. ( https://github.com/regro/cf-scripts/issues/54 )

**Comment by beckermr** [comment]
fixed with github actions for rerendering
