### ISSUE TITLE
Add admin command to enable a migration

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/conda-forge-webservices#351]
We can add an admin command that enables migration given its name in the pinnings repo. for example conda-forge-admin add python38 migration would add the correct current migration yaml and rerender the feedstock.

**Comment by isuruf** [comment]
You used a different timestamp than the one in the pinning file and the bot thinks that it is an old one. In the second attempt you created it correctly.

**Comment by beckermr** [comment]
I asked them to open this issue. The contents might be wrong but the issue is correct. We can make an admin command to copy the correct migration to the feedstock and rerender.

**Comment by CJ-Wright** [comment]
Why would you want to run a migration before the bot got to the repo? Most likely the migration would be DOA. If not then we should increase the migration rate.

**Comment by beckermr** [comment]
The python38 migration is a great example. Lots of people have added it and it worked fine.

**Comment by Anthchirp** [comment]
I had a case where a repository was archived and thus missed out on the migration (https://github.com/conda-forge/orderedset-feedstock/pull/5)

I don't know whether the bot would have picked this up eventually

**Comment by CJ-Wright** [comment]
In the case where the repo was archived something else needs to be done, since that is completely excluded from the graph. The bot currently doesn't have a mechanism to know when an archived repo becomes unarchived so this would only fix the problem superficially?

@beckermr can you give examples? In that case maybe the migration should have made those PRs but didn't.

**Comment by beckermr** [comment]
I lost track of them, but this has happened several times during the python38 migration with people asking in gitter. 

I agree it is probably the bot making an error. However, I don't see the harm in giving ppl an easy way to fix bot errors. The bot will never be perfect and this is a nice way to let others help us during big migrations.

**Comment by CJ-Wright** [comment]
Except that this isn't fixing the bot's error, since it isn't fixing the bot's bad data, especially as this is a very temporary fix. The next time there is a migration or version bump the bot's data will still be wrong. (See @Anthchirp's example of the archived feedstock)

If the bot has bad data we should fix that at the source.

My concern is that most times those PRs will error due to missing dependencies. Either a PR is ready to be issued or it isn't and if it is ready then it should be issued if it isn't it should not, I don't see much room for a maintainer's opinion here.

**Comment by beckermr** [comment]
I don't agree, but I also don't have plans to implement code against this issue anytime soon. :)

**Comment by CJ-Wright** [comment]
@Anthchirp can you please open an issue against the bot's graph (regro/cf-graph-countyfair) to add your feedstock back to the graph?

**Comment by beckermr** [comment]
I got it @Anthchirp. You have already helped a lot! Thank you!

**Comment by jakirkham** [comment]
What if there is a command to ask the bot to add a repo to the migration? Maybe this addresses both concerns? 🙂

**Comment by jakirkham** [comment]
Also related ( https://github.com/regro/cf-scripts/issues/692 ).
