### ISSUE TITLE
Rerendering bot broken when GHA workflow files change

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-webservices#568]
When we use Github Actions as a CI service, the rerender changes those.
The rerendering bot when we use `@ conda-forge-admin, rerender` starts a Github action
to rerender the feedstock and push to the repo. However the github token given to
Github action has limited scope and cannot push to the feedstock. This is a security
feature.

We haven't had GHA as a CI service for feedstock as we've been using Azure
and other CI. Once we do add GHA for self-hosted jobs, we can't rerender those
feedstocks using the bot and we have to do this locally.

cc @conda-forge/core

**Comment by beckermr** [comment]
I had a solution coded up for this. It would use our webservices GitHub app to generate a short-lived token scoped to a single feedstock. It then added this token to the feedstocks secrets before it kicked off the rerender job. I finally setup the rerender jobs to attempt to use this token instead of the built-in one. 

I stripped this code out of this repository however. I wasn't comfortable with the security issues even though the tokens themselves had minimal permissions. 

If someone wants to take a closer look at this, we can dig up the code from the history.

**Comment by beckermr** [comment]
this is now fixed!
