### ISSUE TITLE
Linter doesn't like the "UNLICENSE"

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/conda-forge-webservices#94]
[`urlobject`](https://github.com/conda-forge/staged-recipes/pull/2452) uses the ["UNLICENSE"](https://github.com/zacharyvoase/urlobject/blob/master/UNLICENSE) as its license. This gets the linter mad because it includes the word "license".

**Comment by jakirkham** [comment]
Why not just say it is Public Domain?

**Comment by pmlandwehr** [comment]
Fair point...

**Comment by dopplershift** [comment]
Because it's only Public Domain in jurisdictions that recognize it.

The correct solution is to whitelist UNLICENSE in the linter. We should list what packages actually use, not interpret it. Fix the tool, not bend to its will.

**Comment by jakirkham** [comment]
What exactly is the difference between the two? Why would UNLICENSE work better and/or avoid issues with putting content into the public domain? AFAICT they are the same thing.

**Comment by dopplershift** [comment]
It goes beyond public domain dedication by adding the warranty disclaimer--so it's actually more.

```
The Unlicense is a template for disclaiming copyright monopoly interest in software you've written; in other words, it is a template for dedicating your software to the public domain. It combines a copyright waiver patterned after the very successful public domain SQLite project with the no-warranty statement from the widely-used MIT/X11 license.
```

IMO, it's a specific version of public domain, like LGPL is a specific entry in the GPL family.

**Comment by ocefpaf** [comment]
This linter rule is nonsensical and only modify us recipes and bend
metadata. It has to go!

On Feb 26, 2017 10:43 PM, "Ryan May" <notifications@github.com> wrote:

It goes beyond public domain dedication by adding the warranty
disclaimer--so it's actually more.

The Unlicense is a template for disclaiming copyright monopoly
interest in software you've written; in other words, it is a template
for dedicating your software to the public domain. It combines a
copyright waiver patterned after the very successful public domain
SQLite project with the no-warranty statement from the widely-used
MIT/X11 license.

IMO, it's a specific version of public domain, like LGPL is a specific
entry in the GPL family.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/conda-forge-webservices/issues/94#issuecomment-282608552>,
or mute the thread
